name: Ruby CI

on: [push, pull_request] # push OR PR

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 3.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby and Bundle Install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
      run: bundle exec rake